O_Chef_Pro/src/Entity/Country.php
<?php

namespace App\Entity;

use App\Repository\CountryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;


/**
 * @ORM\Entity(repositoryClass=CountryRepository::class)
 * @ApiResource
 */
class Country
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $picture;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity=Recipe::class, mappedBy="countries")
     */
    private $recipes;

    /**
     * @ORM\ManyToOne(targetEntity=Region::class, inversedBy="countries")
     */
    private $region;

    public function __construct()
    {
        $this->recipes = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Recipe[]
     */
    public function getRecipes(): Collection
    {
        return $this->recipes;
    }

    public function addRecipe(Recipe $recipe): self
    {
        if (!$this->recipes->contains($recipe)) {
            $this->recipes[] = $recipe;
            $recipe->setCountries($this);
        }

        return $this;
    }

    public function removeRecipe(Recipe $recipe): self
    {
        if ($this->recipes->removeElement($recipe)) {
            // set the owning side to null (unless already changed)
            if ($recipe->getCountries() === $this) {
                $recipe->setCountries(null);
            }
        }

        return $this;
    }

    public function getRegion(): ?Region
    {
        return $this->region;
    }

    public function setRegion(?Region $region): self
    {
        $this->region = $region;

        return $this;
    }
}

O_Chef_Pro/src/Form/CountryType.php
<?php

namespace App\Form;

use App\Entity\Country;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CountryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('picture')
            ->add('description')
            ->add('region')
           
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Country::class,
        ]);
    }
}

O_Chef_Pro/src/Controller/Admin/CountryController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Country;
use App\Form\CountryType;
use App\Repository\CountryRepository;
use App\Repository\RegionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/country")
 */
class CountryController extends AbstractController
{
    /**
     * @Route("/", name="admin_country_index", methods={"GET"})
     */
    public function index(CountryRepository $countryRepository, RegionRepository $regionRepository): Response
    {
        return $this->render('back/country/index.html.twig', [
            'countries' => $countryRepository->findAll(),
            'regions' => $regionRepository->findAll()
        ]);
    }

    /**
     * @Route("/new", name="admin_country_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $country = new Country();
        $form = $this->createForm(CountryType::class, $country);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $country->setCreatedAt(new \datetime());
            $country->setUpdatedAt(new \datetime());

            $entityManager->persist($country);
            $entityManager->flush();

            return $this->redirectToRoute('admin_country_index');
        }

        return $this->render('back/country/new.html.twig', [
            'country' => $country,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_country_show", methods={"GET"})
     */
    public function show(Country $country): Response
    {
        return $this->render('back/country/show.html.twig', [
            'country' => $country,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_country_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Country $country): Response
    {
        $form = $this->createForm(CountryType::class, $country);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_country_index');
        }

        return $this->render('back/country/edit.html.twig', [
            'country' => $country,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_country_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Country $country): Response
    {
        if ($this->isCsrfTokenValid('delete'.$country->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($country);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_country_index');
    }
}

O_Chef_Pro/src/Controller/Front/CountryController.php
<?php

namespace App\Controller\Front;

use App\Entity\Country;
use App\Form\CountryType;
use App\Repository\CountryRepository;
use App\Repository\RegionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/country")
 */
class CountryController extends AbstractController
{
    /**
     * @Route("/", name="country_index", methods={"GET"})
     */
    public function index(CountryRepository $countryRepository): Response
    {
        
        return $this->render('front/country/index.html.twig', [
            'countries' => $countryRepository->findAll(),
        ]);
    }


    /**
     * @Route("/{id}", name="country_show", methods={"GET"})
     */
    public function show(Country $country): Response
    {
        return $this->render('front/country/show.html.twig', [
            'country' => $country,
        ]);
    }

}

O_Chef_Pro/templates/back/country/_delete_form.html.twig
<form method="post" action="{{ path('admin_country_delete', {'id': country.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ country.id) }}">
    <button class="btn">Delete</button>
</form>

O_Chef_Pro/templates/back/country/edit.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}Edit Country{% endblock %}

{% block body %}
    <h1>Edit Country</h1>

    {{ include('back/country/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('admin_country_index') }}">back to list</a>

    {{ include('back/country/_delete_form.html.twig') }}
{% endblock %}

O_Chef_Pro/templates/back/country/index.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}Liste des Pays{% endblock %}

{% block body %}


<h1> Liste des Pays</h1>


<br>

<div class="d-grid gap-2 col-4 mx-auto">
 <button type="button" class="btn btn-outline-dark"><a href="{{ path('admin_country_new') }}">Créer un nouveau Pays</a></button>
</div>

<br>

<div class="container">
<div class="row row-cols-2 row-cols-lg-6 g-2 g-lg-2">


{% for region in regions %}
<button class="btn dropdown-toggle btn-outline-dark" region="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="true">
  <div class="btn "><li class="list-group-item"><a href="{{ path('admin_region_show', {id : region.id}) }}">{{ region.name }}</a></li></div>
</button>
 
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
 
   {% for regionCountry in region.countries %}
    <div class="btn btn-outline-dark"><li class="list-group-item"><a href="{{ path('admin_country_show', {id : regionCountry.id }) }}">{{ regionCountry.name }} 
  </a></li></div> 
   {% endfor %}   

</ul>
   {% endfor %}
   </div>
</div>


<br>
 
<a href="{{ path('homepage') }}">Back to homepage</a>

{% endblock %}

O_Chef_Pro/templates/back/country/new.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}New Country{% endblock %}

{% block body %}
    <h1>Create new Country</h1>

    {{ include('back/country/_form.html.twig') }}

    <a href="{{ path('admin_country_index') }}">back to list</a>
{% endblock %}

O_Chef_Pro/templates/back/country/show.html.twig
{% extends 'back/base.html.twig' %}



{% block body %}
   {% block title %}<h1>{{ country.name }}</h1>{% endblock %}

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ country.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ country.name }}</td>
            </tr>
            <tr>
                <th>Picture</th>
                <td>{{ country.picture }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ country.description }}</td>
            </tr>
            <tr>
                <th>Recettes tag</th>
                {% for recipe in country.recipes %}
                <td><a href="{{ path('admin_recipe_show', {id : recipe.id }) }}">{{ recipe.name }}</a></td>
                {% endfor %}
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ country.createdAt ? country.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ country.updatedAt ? country.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('admin_country_index') }}">back to list</a>

    <a href="{{ path('admin_country_edit', {'id': country.id}) }}">edit</a>

    {{ include('back/country/_delete_form.html.twig') }}
{% endblock %}